version: '3'

services:
  nginx:
    build: nginx
    container_name: g-framework-nginx
    ports:
      - ${APP_PORT}:80
    volumes:
      - ..:/var/www/vhosts/g-framework
      - ./nginx/g-framework-conf.conf:/etc/nginx/conf.d/g-framework.conf
    depends_on:
      - php

  php:
    container_name: g-framework-php
    build: php
    volumes:
      - ..:/var/www/vhosts/g-framework

volumes:
  db-data:

networks:
  default:
    name: g-framework

